### ISSUE TITLE
 error: org.w3c.dom.DOMException: android.support.v7.app.ActionBar$Tab

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1347]
Hello I'm getting this error on couple of pages of the new app:
- Catalogue when trying to click any category (WOMEN, MEN, etc.. weirdly only occurs if country France is selected)
- getting the text from top bar
- My offers & orders page

Exception: 

[MJSONWP] Encountered internal error running command:  {"jsonwp":{"sessionId":"467b0f61-8b36-408d-b9f4-931e002d117f","status":13,"value":"org.w3c.dom.DOMException: android.support.v7.app.ActionBar$Tab\n\tat org.apache.harmony.xml.dom.NodeImpl.setName(NodeImpl.java:286)\n\tat org.apache.harmony.xml.dom.ElementImpl.<init>(ElementImpl.java:56)\n\tat org.apache.harmony.xml.dom.DocumentImpl.createElement(DocumentImpl.java:344)\n\tat org.apache.harmony.xml.dom.DocumentImpl.createElement(DocumentImpl.java:48)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:150)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.find(XPathFinder.java:88)\n\tat io.appium.uiautomator2.model.XPathFinder.getNodesList(XPathFinder.java:120)\n\tat io.appium.uiautomator2.handler.FindElement.getXPathUiObject(FindElement.java:77)\n\tat io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:152)\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:101)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:54)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:201)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:192)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\n\tat java.lang.Thread.run(Thread.java:818)\n"}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"sessionId":"467b0f61-8b36-408d-b9f4-931e002d117f","status":13,"value":"org.w3c.dom.DOMException: android.support.v7.app.ActionBar$Tab\n\tat org.apache.harmony.xml.dom.NodeImpl.setName(NodeImpl.java:286)\n\tat org.apache.harmony.xml.dom.ElementImpl.<init>(ElementImpl.java:56)\n\tat org.apache.harmony.xml.dom.DocumentImpl.createElement(DocumentImpl.java:344)\n\tat org.apache.harmony.xml.dom.DocumentImpl.createElement(DocumentImpl.java:48)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:150)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179)\n\tat io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140)\n\tat io.appium.uiautomator2.model.XPathFinder.find(XPathFinder.java:88)\n\tat io.appium.uiautomator2.model.XPathFinder.getNodesList(XPathFinder.java:120)\n\tat io.appium.uiautomator2.handler.FindElement.getXPathUiObject(FindElement.java:77)\n\tat io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:152)\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:101)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:54)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:201)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:192)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\n\tat java.lang.Thread.run(Thread.java:818)\n"}
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/Users/itsqdtests/appium/sources/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/itsqdtests/appium/sources/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/itsqdtests/appium/sources/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/itsqdtests/appium/sources/node_modules/babel-runtime/regenerator/runtime.js:136:37)

I've tried the suggested in https://github.com/appium/appium/issues/7524 but didnt work.

Any clue how to solve this?

Thanks and regards

Cerberus Version : 1.1.13-SNAPSHOT-1151

**Comment by j0hnsa** [comment]
For instance the same test:
FR : http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=47840611 -> KO
INTER : http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=47840701 -> OK

**Comment by j0hnsa** [comment]
Solved with the latest appium and changing where getFromHtml to getAttributeFromHtml (name).

Regards

**Comment by umashankaryadagiri1** [comment]
is there any solution for the above issue because same kind of issue occurs me as well,

[RemoteTestNG] detected TestNG version 6.11.0
Jun 07, 2018 5:17:47 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
NATIVE_APP
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: org.w3c.dom.DOMException: o.?
	at org.apache.harmony.xml.dom.NodeImpl.setName(NodeImpl.java:286)
	at org.apache.harmony.xml.dom.ElementImpl.<init>(ElementImpl.java:56)
	at org.apache.harmony.xml.dom.DocumentImpl.createElement(DocumentImpl.java:344)
	at org.apache.harmony.xml.dom.DocumentImpl.createElement(DocumentImpl.java:48)
	at io.appium.uiautomator2.model.XPathFinder.toDOMElement(XPathFinder.java:85)
	at io.appium.uiautomator2.model.XPathFinder.toDOMElement(XPathFinder.java:125)
	at io.appium.uiautomator2.model.XPathFinder.toDOMElement(XPathFinder.java:125)
	at io.appium.uiautomator2.model.XPathFinder.toDOMElement(XPathFinder.java:125)
	at io.appium.uiautomator2.model.XPathFinder.toDOMElement(XPathFinder.java:125)
	at io.appium.uiautomator2.model.XPathFinder.toDOMElement(XPathFinder.java:125)
	at io.appium.uiautomator2.model.XPathFinder.toDOMElement(XPathFinder.java:125)
	at io.appium.uiautomator2.model.XPathFinder.toDOMElement(XPathFinder.java:125)
	at io.appium.uiautomator2.model.XPathFinder.find(XPathFinder.java:218)
	at io.appium.uiautomator2.model.XPathFinder.getNodesList(XPathFinder.java:66)
	at io.appium.uiautomator2.handler.FindElement.getXPathUiObject(FindElement.java:75)
	at io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:140)
	at io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:114)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:65)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:247)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:238)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:818)
 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'Q69DWS69', ip: '172.16.50.7', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_102'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.tmw.mobilewallet.activi..., appPackage: com.tmw.mobilewallet, automationName: uiautomator2, databaseEnabled: false, desired: {appActivity: com.tmw.mobilewallet.activi..., appPackage: com.tmw.mobilewallet, automationName: uiautomator2, deviceName: Android Device, platformName: Android}, deviceApiLevel: 23, deviceManufacturer: Xiaomi, deviceModel: Redmi 4A, deviceName: 667d74c1f4c4, deviceScreenDensity: 320, deviceScreenSize: 720x1280, deviceUDID: 667d74c1f4c4, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2, platform: LINUX, platformName: LINUX, platformVersion: 6.0.1, statBarHeight: 48, takesScreenshot: true, viewportRect: {height: 1232, left: 0, top: 48, width: 720}, warnings: {}, webStorageEnabled: false}
Session ID: b7f98e37-543e-4d5a-a451-07542966f6a2
*** Element info: {Using=xpath, value=.//android.widget.TextView[@text='Gold']}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:371)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:473)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:140)
	at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementByXPath(AndroidDriver.java:1)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:58)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriPASSED: ent
ver.java:1)
	at Demo.ent(Demo.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================

Solution for this will be a great helpful
