### ISSUE TITLE
java.sql.BatchUpdateException: Data too long for column 'DataLib'

### ISSUE THREAD

**Issue by mbessa** [cerberustesting/cerberus-source#1631]
Hello,

We detected another issue in testcaseexecutiondata, data too long for DataLib:

Logs:
[#|2018-02-27T13:00:11.599+0100|INFO|glassfish 4.1||_ThreadID=86;_ThreadName=Thread-9;_TimeMillis=1519732811599;_LevelValue=800;|
  2018-02-27 13:00:11 ERROR TestCaseExecutionDataDAO:541 - Unable to execute query : java.sql.BatchUpdateException: Data too long for column 'DataLib' at row 1
Query is: INSERT INTO testcaseexecutiondata (`id`, `property`, `index`, `description`, `value`, `type`, `value1`, `value2`, `rc`, `rmessage`, `start`, `end`, `startlong`, `endlong`, `database`, `value1Init`,`value2Init`,`lengthInit`,`length`, `rowLimit`, `nature`, `retrynb`, `retryperiod`, `system`, `environment`, `country`, `dataLib`, `jsonResult`, `FromCache`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
Query is:
INSERT INTO testcaseexecutiondata (`id`, `property`, `index`, `description`, `value`, `type`, `value1`, `value2`, `rc`, `rmessage`, `start`, `end`, `startlong`, `endlong`, `database`, `value1Init`,`value2Init`,`lengthInit`,`length`, `rowLimit`, `nature`, `retrynb`, `retryperiod`, `system`, `environment`, `country`, `dataLib`, `jsonResult`, `FromCache`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)|#]

[#|2018-02-27T13:00:11.600+0100|INFO|glassfish 4.1||_ThreadID=86;_ThreadName=Thread-9;_TimeMillis=1519732811600;_LevelValue=800;|
  2018-02-27 13:00:11 ERROR PropertyService:229 - null
org.cerberus.exception.CerberusException: null
        at org.cerberus.crud.service.impl.TestCaseExecutionDataService.convert(TestCaseExecutionDataService.java:151) ~[TestCaseExecutionDataService.class:?]
        at org.cerberus.engine.gwt.impl.PropertyService.decodeStringWithExistingProperties(PropertyService.java:212) [PropertyService.class:?]
        at org.cerberus.engine.gwt.impl.VariableService.decodeStringCompletly(VariableService.java:136) [VariableService.class:?]
        at org.cerberus.engine.gwt.impl.ControlService.doControl(ControlService.java:105) [ControlService.class:?]
        at org.cerberus.engine.execution.impl.ExecutionRunService.executeControl(ExecutionRunService.java:1261) [ExecutionRunService.class:?]
        at org.cerberus.engine.execution.impl.ExecutionRunService.executeAction(ExecutionRunService.java:1137) [ExecutionRunService.class:?]
        at org.cerberus.engine.execution.impl.ExecutionRunService.executeStep(ExecutionRunService.java:908) [ExecutionRunService.class:?]
        at org.cerberus.engine.execution.impl.ExecutionRunService.executeTestCase(ExecutionRunService.java:529) [ExecutionRunService.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338) [spring-aop-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206) [spring-aop-5.0.0.RELEASE.jar:5.0.0.RELEASE]
        at com.sun.proxy.$Proxy259.executeTestCase(Unknown Source) [?:?]
        at org.cerberus.engine.execution.impl.RunTestCaseService.runTestCase(RunTestCaseService.java:77) [RunTestCaseService.class:?]
        at org.cerberus.servlet.zzpublic.RunTestCase.doGet(RunTestCase.java:346) [RunTestCase.class:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [javax.servlet-api.jar:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api.jar:3.1.0]
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682) [web-core.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344) [web-core.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [web-core.jar:?]
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:305) [tyrus-container-servlet.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256) [web-core.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [web-core.jar:?]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316) [web-core.jar:?]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160) [web-core.jar:?]
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734) [web-core.jar:?]
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673) [web-core.jar:?]
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99) [web-glue.jar:?]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174) [web-core.jar:?]
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416) [web-core.jar:?]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283) [web-core.jar:?]
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459) [kernel.jar:?]
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167) [kernel.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [nucleus-grizzly-all.jar:?]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [nucleus-grizzly-all.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]|#]

**Comment by ffazendeiro** [comment]
Hi,
The error message is not very clear in this kind of errors (data too long).
In this case the DataLib name have 50 characters (above 45 defined in testcaseexecutiondata; Datalib could be created because in testdatalib name is defined to 200 max characters) and we have a recursive error:
![image](https://user-images.githubusercontent.com/17747042/36728547-ffd9c3c2-1bb8-11e8-9009-93696430b6aa.png)

Cerberus version: 3.2.0-SNAPSHOT-1292

**Comment by vertigo17** [comment]
fixed with https://github.com/cerberustesting/cerberus-source/commit/3904978d854218d005c36ec75ba85f3a65b332ee
