### ISSUE TITLE
fix log4j exception.

### ISSUE THREAD

**Issue by vertigo17** [cerberustesting/cerberus-source#1669]
Grave:   Exception while visiting META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil.class of size 778
java.lang.IllegalArgumentException
	at org.glassfish.hk2.external.org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	at org.glassfish.hk2.external.org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
	at org.glassfish.hk2.external.org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
	at org.glassfish.hk2.classmodel.reflect.Parser$5.on(Parser.java:359)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.handleEntry(ReadableArchiveScannerAdapter.java:165)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.onSelectedEntries(ReadableArchiveScannerAdapter.java:127)
	at org.glassfish.hk2.classmodel.reflect.Parser.doJob(Parser.java:345)
	at org.glassfish.hk2.classmodel.reflect.Parser.access$300(Parser.java:68)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:304)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Grave:   Exception while visiting META-INF/versions/9/org/apache/logging/log4j/util/StackLocator.class of size 7264
java.lang.IllegalArgumentException
	at org.glassfish.hk2.external.org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	at org.glassfish.hk2.external.org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
	at org.glassfish.hk2.external.org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
	at org.glassfish.hk2.classmodel.reflect.Parser$5.on(Parser.java:359)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.handleEntry(ReadableArchiveScannerAdapter.java:165)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.onSelectedEntries(ReadableArchiveScannerAdapter.java:127)
	at org.glassfish.hk2.classmodel.reflect.Parser.doJob(Parser.java:345)
	at org.glassfish.hk2.classmodel.reflect.Parser.access$300(Parser.java:68)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:304)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vertigo17** [comment]
Fixed using glassfish 5.
I close it as we will soon move support to Glassfish 5.
