### ISSUE TITLE
Build Content is no longer sent in communication

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#2126]
With previous version, from /Environment.jsp, using Environment activation (Enable Environment with new Build Revision), we were able to send notifications with the build content.
Since the deploy of version V4.7-SNAPSHOT-1485 it is no longer working; build content is empty.

This is useful to send the subjects/content to the specified lists/users.

Example before SNAPSHOT-1485:
![imagem](https://user-images.githubusercontent.com/5640464/79999472-d96c7e80-84b3-11ea-9730-d09dfa5be17b.png)

After deploy of SNAPSHOT-1485:
![imagem](https://user-images.githubusercontent.com/5640464/79999416-ca85cc00-84b3-11ea-920f-e81031273a11.png)

Please confirm this is also happening for you and solve it.

**Comment by gmoita** [comment]
From logs, it is related to the removal of table `project`.

  2020-04-22 17:22:32 WARN  EmailBodyGeneration:185 - Cerberus-4.7-SNAPSHOT - Exception catched.
java.sql.SQLSyntaxErrorException: Table 'cerberus.project' doesn't exist
Query is : SELECT b.`Build`, b.`Revision`, b.`Release` , b.`Link` ,  b.`Application`, b.`ReleaseOwner`, b.`BugIDFixed`, b.`TicketIDFixed`, b.`subject`, b.`Project`, p.`VCCode`, u.Name, a.BugTrackerUrl  from buildrevisionparameters b  left outer join project p on p.idproject=b.project  left outer join user u on u.Login=b.ReleaseOwner  left outer join application a on a.application=b.application  join buildrevisioninvariant bri on bri.versionname = b.revision and bri.`system` = 'common'  and bri.`level` = 2  where build = 'common20' and a.system = 'common'  and bri.seq > (select seq from buildrevisioninvariant where `system` = 'common' and `level` = 2 and `versionname` = 'R000' )   and bri.seq <= (select seq from buildrevisioninvariant where `system` = 'common' and `level` = 2 and `versionname` = 'R001' )   order by b.Build, bri.seq, b.Application, b.datecre, b.TicketIDFixed, b.BugIDFixed, b.`Release`
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125) ~[mariadb-java-client-1.4.4.jar:?]
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69) ~[mariadb-java-client-1.4.4.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:250) ~[mariadb-java-client-1.4.4.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:278) ~[mariadb-java-client-1.4.4.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:391) ~[mariadb-java-client-1.4.4.jar:?]
        at com.sun.gjc.spi.jdbc40.StatementWrapper40.executeQuery(StatementWrapper40.java:234) ~[__ds_jdbc_ra.jar:?]
        at org.cerberus.service.email.impl.EmailBodyGeneration.GenerateBuildContentTable(EmailBodyGeneration.java:95) [EmailBodyGeneration.class:?]
        at org.cerberus.service.email.impl.EmailGenerationService.generateRevisionChangeEmail(EmailGenerationService.java:119) [EmailGenerationService.class:?]
        at org.cerberus.servlet.integration.GetNotification.processRequest(GetNotification.java:111) [GetNotification.class:?]
        at org.cerberus.servlet.integration.GetNotification.doGet(GetNotification.java:194) [GetNotification.class:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [javax.servlet-api.jar:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api.jar:3.1.0]

Please fix this.
