### ISSUE TITLE
No screenshot taken on error

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2186]
Hello, 

No screenshot was taken during this execution, even after a reload of the page
![image](https://user-images.githubusercontent.com/30227758/95206941-96932e80-07e7-11eb-8478-af7bc5c7b436.png)

According to the appium log: the screenshot command was not triggered:

```
Got response with status 200: {"sessionId":"926ffb8c-5ef4-4ebd-8f3d-b73a1f76dd90","value":{"height":139,"width":353}}
[debug] [WD Proxy] Proxying [POST /appium/tap] to [POST http://127.0.0.1:8200/wd/hub/session/926ffb8c-5ef4-4ebd-8f3d-b73a1f76dd90/appium/tap] with body: {"x":1263.5,"y":2810.5,"undefined":null}
[WD Proxy] Got response with status 400: {"sessionId":"926ffb8c-5ef4-4ebd-8f3d-b73a1f76dd90","value":{"error":"invalid argument","message":"Coordinate [x=1263.5, y=2810.5] is outside of element rect: [0,0][1440,2672]","stacktrace":"io.appium.uiautomator2.common.exceptions.InvalidCoordinatesException: Coordinate [x=1263.5, y=2810.5] is outside of element rect: [0,0][1440,2672]\n\tat io.appium.uiautomator2.utils.PositionHelper.getAbsolutePosition(PositionHelper.java:64)\n\tat io.appium.uiautomator2.utils.PositionHelper.getDeviceAbsPos(PositionHelper.java:73)\n\tat io.appium.uiautomator2.handler.Tap.safeHandle(Tap.java:54)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:253)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:247)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(A...
[debug] [W3C] Matched W3C error code 'invalid argument' to InvalidArgumentError
[debug] [W3C (dc4ebc79)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.InvalidCoordinatesException: Coordinate [x=1263.5, y=2810.5] is outside of element rect: [0,0][1440,2672]
[debug] [W3C (dc4ebc79)] 	at io.appium.uiautomator2.utils.PositionHelper.getAbsolutePosition(PositionHelper.java:64)
[debug] [W3C (dc4ebc79)] 	at io.appium.uiautomator2.utils.PositionHelper.getDeviceAbsPos(PositionHelper.java:73)
[debug] [W3C (dc4ebc79)] 	at io.appium.uiautomator2.handler.Tap.safeHandle(Tap.java:54)
[debug] [W3C (dc4ebc79)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)
[debug] [W3C (dc4ebc79)] 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:253)
[debug] [W3C (dc4ebc79)] 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:247)
[debug] [W3C (dc4ebc79)] 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (dc4ebc79)] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[debug] [W3C (dc4ebc79)] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[debug] [W3C (dc4ebc79)] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (dc4ebc79)] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
[debug] [W3C (dc4ebc79)] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[debug] [W3C (dc4ebc79)] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[debug] [W3C (dc4ebc79)] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[debug] [W3C (dc4ebc79)] 	at java.lang.Thread.run(Thread.java:764)
[debug] [W3C (dc4ebc79)] 
[HTTP] <-- POST /wd/hub/session/dc4ebc79-b673-4ee6-8438-a90e5040932e/touch/perform 400 283 ms - 3946
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/dc4ebc79-b673-4ee6-8438-a90e5040932e
[HTTP] {}
[debug] [W3C (dc4ebc79)] Calling AppiumDriver.deleteSession() with args: ["dc4ebc79-b673-4ee6-8438-a90e5040932e"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1601990368518 (15:19:28 GMT+0200 (heure d’été d’Europe centrale))
[Appium] Removing session dc4ebc79-b673-4ee6-8438-a90e5040932e from our master session list
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/wd/hub/session/926ffb8c-5ef4-4ebd-8f3d-b73a1f76dd90] with no body
[debug] [WD Proxy] Got response with status 200: {"sessionId":"926ffb8c-5ef4-4ebd-8f3d-b73a1f76dd90","value":null}
[debug] [ADB] Running '/Users/BAPTISTE/Library/Android/sdk/platform-tools/adb -P 5037 -s LGH870621c6a73 shell am force-stop com.oxylane.android.cubeinstore.debug'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/BAPTISTE/Library/Android/sdk/platform-tools/adb -P 5037 -s LGH870621c6a73 forward --remove tcp\:8200'
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1601990368746 (15:19:28 GMT+0200 (heure d’été d’Europe centrale))
[debug] [W3C (dc4ebc79)] Received response: null
[debug] [W3C (dc4ebc79)] But deleting session, so not returning
[debug] [W3C (dc4ebc79)] Responding to client with driver.deleteSession() result: null
[debug] [W3C (dc4ebc79)] Destroying socket connection
[HTTP] <-- DELETE /wd/hub/session/dc4ebc79-b673-4ee6-8438-a90e5040932e 200 230 ms - 14
[HTTP] 
[debug] [Instrumentation] .
[debug] [Instrumentation] Time: 37,187
[debug] [Instrumentation] 
[debug] [Instrumentation] OK (1 test)
[debug] [Instrumentation] The process has exited with code 0
```

Thanks!

**Comment by vertigo17** [comment]
Can you specify what was the action triggered ?

**Comment by Nouxx** [comment]
It was a click (on Android), the error itself is under investigation but I suspect that is issue comes from the mobile application itself

**Comment by Nouxx** [comment]
Same situation when a property is not present (so an implementation problem)
![image](https://user-images.githubusercontent.com/30227758/95963036-7119ac80-0e07-11eb-84af-537475068288.png)

In this case, it would help me save time seeing the label I forgot to implement in the screenshot

**Comment by vertigo17** [comment]
For the 1st one looks like connection to srlenium/appium was list

**Comment by Nouxx** [comment]
Ok for the first one, it seems appium is forcing the stop after such error, which leaves no time for cerberus to trigger the screenshot.

However, I would expect it to take a screenshot if any action fails, even if it's an implementation problem (second one)
