### ISSUE TITLE
Upgrade xpath library

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2212]
Hi,

I'd like to use `matches()` function from xpath, you can find a reference of it [here](https://stackoverflow.com/a/2893899)

But, using it in Cerberus seems not possible:

xpath used : `xpath=.//*[@resource-id="com.oxylane.android.cubeinstore.debug:id/text_customer_name" and matches(@text,'Clément','i')]`

result in Cerberus: `The test case is cancelled due to lost connection to Selenium Server! Detailed error : An unknown server-side error occurred while processing the command. Original error: java.lang.IllegalStateException: Unable to evaluate expression. See cause`

It may be related to the version of xpath Cerberus is using, which I believe come from this dependency : `xmlunit` (from source/pom.xml)

It's working on [xpather](http://xpather.com) but I'm not sure which version it's using..

Can we investigate this?

here is the full log from Appium:
```
[debug] [W3C (c2a75a52)] 	at io.appium.uiautomator2.core.AccessibilityNodeInfoDumper.findNodes(AccessibilityNodeInfoDumper.java:244)
[debug] [W3C (c2a75a52)] 	at io.appium.uiautomator2.utils.ElementLocationHelpers.getXPathNodeMatch(ElementLocationHelpers.java:111)
[debug] [W3C (c2a75a52)] 	at io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:94)
[debug] [W3C (c2a75a52)] 	at io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:71)
[debug] [W3C (c2a75a52)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)
[debug] [W3C (c2a75a52)] 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:253)
[debug] [W3C (c2a75a52)] 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:247)
[debug] [W3C (c2a75a52)] 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (c2a75a52)] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[debug] [W3C (c2a75a52)] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[debug] [W3C (c2a75a52)] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (c2a75a52)] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
[debug] [W3C (c2a75a52)] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[debug] [W3C (c2a75a52)] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[debug] [W3C (c2a75a52)] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[debug] [W3C (c2a75a52)] 	at java.lang.Thread.run(Thread.java:761)
[debug] [W3C (c2a75a52)] Caused by: java.lang.IllegalStateException: Unable to evaluate expression. See cause
[debug] [W3C (c2a75a52)] 	at org.jdom2.xpath.jaxen.JaxenCompiled.evaluateRawAll(JaxenCompiled.java:200)
[debug] [W3C (c2a75a52)] 	at org.jdom2.xpath.util.AbstractXPathCompiled.evaluate(AbstractXPathCompiled.java:356)
[debug] [W3C (c2a75a52)] 	at io.appium.uiautomator2.core.AccessibilityNodeInfoDumper.findNodes(AccessibilityNodeInfoDumper.java:225)
[debug] [W3C (c2a75a52)] 	... 37 more
[debug] [W3C (c2a75a52)] Caused by: org.jaxen.UnresolvableException: No Such Function matches
[debug] [W3C (c2a75a52)] 	at org.jaxen.SimpleFunctionContext.getFunction(SimpleFunctionContext.java:127)
[debug] [W3C (c2a75a52)] 	at org.jaxen.ContextSupport.getFunction(ContextSupport.java:242)
[debug] [W3C (c2a75a52)] 	at org.jaxen.Context.getFunction(Context.java:216)
[debug] [W3C (c2a75a52)] 	at org.jaxen.expr.DefaultFunctionCallExpr.evaluate(DefaultFunctionCallExpr.java:176)
[debug] [W3C (c2a75a52)] 	at org.jaxen.expr.DefaultAndExpr.evaluate(DefaultAndExpr.java:91)
[debug] [W3C (c2a75a52)] 	at org.jaxen.expr.DefaultPredicate.evaluate(DefaultPredicate.java:95)
[debug] [W3C (c2a75a52)] 	at org.jaxen.expr.PredicateSet.applyPredicate(PredicateSet.java:269)
[debug] [W3C (c2a75a52)] 	at org.jaxen.expr.PredicateSet.evaluatePredicates(PredicateSet.java:245)
[debug] [W3C (c2a75a52)] 	at org.jaxen.expr.DefaultNameStep.evaluate(DefaultNameStep.java:291)
[debug] [W3C (c2a75a52)] 	at org.jaxen.expr.DefaultLocationPath.evaluate(DefaultLocationPath.java:140)
[debug] [W3C (c2a75a52)] 	at org.jaxen.expr.DefaultPathExpr.evaluate(DefaultPathExpr.java:137)
[debug] [W3C (c2a75a52)] 	at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:102)
[debug] [W3C (c2a75a52)] 	at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:675)
[debug] [W3C (c2a75a52)] 	at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:215)
[debug] [W3C (c2a75a52)] 	at org.jdom2.xpath.jaxen.JaxenCompiled.evaluateRawAll(JaxenCompiled.java:198)
[debug] [W3C (c2a75a52)] 	... 39 more
[debug] [W3C (c2a75a52)] 
[HTTP] <-- POST /wd/hub/session/c2a75a52-94ac-477c-a62b-1d4531cb88c2/element 500 342 ms - 5700
```

**Comment by vertigo17** [comment]
In fact when pointing to an element, Cerberus does not interpret the value itself but just forward it to Appium / Selenium with the correct mathing type.
In that case it is using 
By.xpath(xpath_value)
Unfortunatly, Appium does not seem to support those xpath ;-(.

**Comment by Nouxx** [comment]
:'( 

issue opened in [appium](https://github.com/appium/appium/issues/14898) FYI
