### ISSUE TITLE
Sikuli - Issue with application Object

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#2227]
Hello,
I met an issue with a test case using Sikuli. It seems Cerberus doesn't find the application object.

Element 'http://cerberus-svc:8080/ReadApplicationObjectImage?application=Signeasy-PDF&object=pdf' is not present on the message/page/screen. - **File http://cerberus-svc:8080/ReadApplicationObjectImage?application=Signeasy-PDF&object=pdf not found. Please verify that url defined in object field is correct and accessible from Cerberus Server.**
(execution time 6ms)

We use an internal link cerberus-svc (kubernetes), but even if we use our cname https://cerberus... or localhost we have the same issue. 
If we click on the url we can see our picture. Png is well present in the folder expected /opt/cerberus/object

**Comment by vertigo17** [comment]
Are there any logs at the application server level ?
On latest snapshot, it works for sure.
I believe you are in 4.10 ?
It must be that this URL is not accessible from Cerberus itself

**Comment by R-Loic** [comment]
We use Cerberus 4.9, we plan to upgrade soon. 
I tried wget from the Cerberus container with all URL possibilites (localhost, cerberus-svc, cname) but everything works as expected. (png is downloaded)
Application, you mean cerberus server side ? Nothing more :/

**Comment by vertigo17** [comment]
Strange indeed.
When did the issue start to appear ? was it linked to a version upgrade ?
Is it on all application object or only some of them ?

Idealy, can you try to reproduce with an earlier version. 4.11 (or above). You can also use snapshot version (it is now available on docker hub).
There were some recent changes on Sikuli engine that could help us to better identify the issue.

**Comment by R-Loic** [comment]
Hello, we tried with the cerberus version 4.11.2.
Issue seems still present with all URLs, error is not the same (stack trace below). I don't know how it works, does cerberus use the cerberus_url parameter to access the file ?
We don't use proxy. Other calls like API are working from Cerberus. Do you have any idea ? 

2021-01-26 13:51:28 WARN  ApplicationObjectDAO:238 - Impossible to read the image
2021-01-26 13:51:35 WARN  SikuliService:273 - java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_212]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_212]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_212]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_212]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_212]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_212]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_212]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_212]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_212]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_212]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_212]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) ~[?:1.8.0_212]
	at org.cerberus.service.sikuli.impl.SikuliService.doSikuliAction(SikuliService.java:204) [classes/:?]
	at org.cerberus.service.sikuli.impl.SikuliService.doSikuliVerifyElementPresent(SikuliService.java:545) [classes/:?]
	at org.cerberus.engine.gwt.impl.ControlService.verifyElementPresent(ControlService.java:621) [classes/:?]
	at org.cerberus.engine.gwt.impl.ControlService.doControl(ControlService.java:251) [classes/:?]
	at org.cerberus.engine.execution.impl.ExecutionRunService.executeControl(ExecutionRunService.java:1584) [classes/:?]
	at org.cerberus.engine.execution.impl.ExecutionRunService.executeAction(ExecutionRunService.java:1450) [classes/:?]
	at org.cerberus.engine.execution.impl.ExecutionRunService.executeStep(ExecutionRunService.java:1178) [classes/:?]
	at org.cerberus.engine.execution.impl.ExecutionRunService.executeTestCase(ExecutionRunService.java:776) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) [spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205) [spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at com.sun.proxy.$Proxy77.executeTestCase(Unknown Source) [?:?]
	at org.cerberus.engine.execution.impl.RunTestCaseService.runTestCase(RunTestCaseService.java:86) [classes/:?]
	at org.cerberus.servlet.zzpublic.RunTestCaseV002.doGet(RunTestCaseV002.java:343) [classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.41]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.41]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.41]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.13.3.jar:2.13.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.41]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.41]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.41]
	at org.keycloak.adapters.tomcat.AbstractAuthenticatedActionsValve.invoke(AbstractAuthenticatedActionsValve.java:67) [keycloak-tomcat-core-adapter-10.0.2.jar:10.0.2]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [catalina.jar:8.5.41]
	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181) [keycloak-tomcat-core-adapter-10.0.2.jar:10.0.2]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) [catalina.jar:8.5.41]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.41]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) [catalina.jar:8.5.41]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.41]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:8.5.41]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) [tomcat-coyote.jar:8.5.41]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.41]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) [tomcat-coyote.jar:8.5.41]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.41]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.41]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.41]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Tony-Clck** [comment]
![image](https://user-images.githubusercontent.com/56879882/105859737-29e9ad00-5fed-11eb-9a44-c931ae419330.png)

**Comment by vertigo17** [comment]
Error is linked with connectivity to Sikuli extension.
Can you try from the docker container to call 
http://SIKULIIP:SIKULIPORT/extra/ExecuteSikuliAction
replacing SIKULIIP and SIKULIPORT from robot host port or executor extension configuration ?
Or share your robot executor configuration.

**Comment by R-Loic** [comment]
Hello we are using sikuli with selenium for an hybride test, it is configured as below :

java -jar selenium-server-standalone-3.141.59.jar -role hub -port **5555**

java -cp selenium-server-standalone-3.141.59.jar:cerberus-extension-sikuli-1.1.7.jar org.openqa.grid.selenium.GridLauncherV3 -role nodehub http://localhost:5555/grid/register -port **5556** -servlets org.sikuliserver.ExecuteSikuliAction

To run test cases we configure sikuli robot with selenium hub > IP:5555
If I try http://SIKULIIP:SIKULIPORT/extra/ExecuteSikuliAction from cerberus container it returns : wget: server returned error: HTTP/1.1 404 Not Found

However, I tried from sikuli localhost to reach the node directly :
curl -XGET "http://localhost:5556/extra/ExecuteSikuliAction"
ExecuteSikuliAction is up and running. Waiting stuff from Cerberus

It seems sikuli is up but how can we configure the sikuli robot ? We must target the hub like other web tests or target the sikuli node ?

**Comment by vertigo17** [comment]
Even if not related to the issue, you should use the latest version of sikuli extention.
It is https://github.com/cerberustesting/cerberus-extension-sikuli/releases/tag/1.3

Then The robot should have a standard Selenium configuration. There are nothing more to configure than a normal Selenium GUI robot.
In order to access the sikuli services, you need to point to the node (not the hub that do not include the servlet). Cerberus does that automaticaly (make sure you use latest version).
This is probably why the 1st access return a 404 as you point to 5555 that correspond to the hub.
The second one that point to 5556 works as it correspond to the node.

**Comment by vertigo17** [comment]
Is the issue still relevent ?

**Comment by vertigo17** [comment]
I close it and let you open it again if necessary.
