### ISSUE TITLE
Cerberus 4.11 Login page missing

### ISSUE THREAD

**Issue by SylvainDumas** [cerberustesting/cerberus-source#2228]
Cerberus Version : 4.11

You can reproduce with https://github.com/cerberustesting/cerberus-source/blob/master/docker/compositions/cerberus-tomcat-mysql/docker-compose.yml and with docker image so

Go on http://localhost:8080 and you get
![image](https://user-images.githubusercontent.com/38704989/103281614-8e582300-49d3-11eb-8080-9db0060d7ec5.png)

You loop on this page when you click on links

Console log give this:
```
cerberus_1  | 29-Dec-2020 11:45:27.056 WARNING [http-nio-8080-exec-5] org.apache.catalina.authenticator.FormAuthenticator.forwardToLoginPage Unexpected error forwarding to login page
cerberus_1  |   org.apache.jasper.JasperException: java.lang.ClassNotFoundException: org.apache.jsp.Login_jsp
cerberus_1  |           at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:197)
cerberus_1  |           at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:413)
cerberus_1  |           at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
cerberus_1  |           at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
cerberus_1  |           at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
cerberus_1  |           at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
cerberus_1  |           at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cerberus_1  |           at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
cerberus_1  |           at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cerberus_1  |           at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cerberus_1  |           at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
cerberus_1  |           at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cerberus_1  |           at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cerberus_1  |           at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
cerberus_1  |           at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
cerberus_1  |           at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
cerberus_1  |           at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
cerberus_1  |           at org.apache.catalina.authenticator.FormAuthenticator.forwardToLoginPage(FormAuthenticator.java:431)
cerberus_1  |           at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:248)
cerberus_1  |           at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:575)
cerberus_1  |           at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
cerberus_1  |           at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
cerberus_1  |           at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
cerberus_1  |           at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
cerberus_1  |           at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
cerberus_1  |           at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
cerberus_1  |           at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
cerberus_1  |           at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
cerberus_1  |           at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
cerberus_1  |           at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
cerberus_1  |           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
cerberus_1  |           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
cerberus_1  |           at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
cerberus_1  |           at java.lang.Thread.run(Thread.java:748)
cerberus_1  |   Caused by: java.lang.ClassNotFoundException: org.apache.jsp.Login_jsp
cerberus_1  |           at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
cerberus_1  |           at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:129)
cerberus_1  |           at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:60)
cerberus_1  |           at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:159)
cerberus_1  |           at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:192)
cerberus_1  |           ... 33 more
cerberus_1  | 29-Dec-2020 11:45:29.866 WARNING [http-nio-8080-exec-7] org.apache.catalina.authenticator.FormAuthenticator.forwardToLoginPage Unexpected error forwarding to login page
cerberus_1  |   org.apache.jasper.JasperException: Unable to compile class for JSP:
cerberus_1  |
cerberus_1  | An error occurred at line: [59] in the jsp file: [/Login.jsp]
cerberus_1  | The method getSQLScript() is undefined for the type IDatabaseVersioningService
cerberus_1  | 56:                 cerberusWelcomeMessage = cerberusWelcomeMessage.replace("%SUPPORTEMAIL%", cerberusSupportEmail);
cerberus_1  | 57:                 String errorMessage = "";
cerberus_1  | 58:                 String display = "";
cerberus_1  | 59:                 String cerberusVersion = Infos.getInstance().getProjectVersion() + "-" + databaseVersionService.getSQLScript().size();
cerberus_1  | 60: 
cerberus_1  | 61:                 if (request.getParameter("error") != null && request.getParameter("error").equalsIgnoreCase("1")) {
cerberus_1  | 62:                     errorMessage = "User or password invalid !!!";
cerberus_1  |
cerberus_1  |
cerberus_1  | Stacktrace:
cerberus_1  |           at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
cerberus_1  |           at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:212)
cerberus_1  |           at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:549)
cerberus_1  |           at org.apache.jasper.compiler.Compiler.compile(Compiler.java:378)
cerberus_1  |           at org.apache.jasper.compiler.Compiler.compile(Compiler.java:350)
cerberus_1  |           at org.apache.jasper.compiler.Compiler.compile(Compiler.java:334)
cerberus_1  |           at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:595)
cerberus_1  |           at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:399)
cerberus_1  |           at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
cerberus_1  |           at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
cerberus_1  |           at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
cerberus_1  |           at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
cerberus_1  |           at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cerberus_1  |           at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
cerberus_1  |           at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cerberus_1  |           at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cerberus_1  |           at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
cerberus_1  |           at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cerberus_1  |           at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cerberus_1  |           at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
cerberus_1  |           at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
cerberus_1  |           at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
cerberus_1  |           at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
cerberus_1  |           at org.apache.catalina.authenticator.FormAuthenticator.forwardToLoginPage(FormAuthenticator.java:431)
cerberus_1  |           at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:248)
cerberus_1  |           at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:575)
cerberus_1  |           at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
cerberus_1  |           at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
cerberus_1  |           at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
cerberus_1  |           at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
cerberus_1  |           at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
cerberus_1  |           at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
cerberus_1  |           at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
cerberus_1  |           at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
cerberus_1  |           at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
cerberus_1  |           at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
cerberus_1  |           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
cerberus_1  |           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
cerberus_1  |           at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
cerberus_1  |           at java.lang.Thread.run(Thread.java:748)
```

**Comment by vertigo17** [comment]
Issue was already fixed with https://github.com/cerberustesting/cerberus-source/commit/7334b88691ad376a32f858a818eef8348ada1818
Workaround until 4.11.1 is release is to use Keycloak.
